import BackArrowLong from "../assets/icons/back-arrow-long.png";
import Lock from "../assets/icons/2fa-lock.png";
import Mobile from "../assets/icons/2fa-mob.png";
import Copy from "../assets/icons/copy-icon.png"
import "./styles/TwoFactorAuth.css";
import UserPermissions from "./UserPermissions";

const TwoFactorAuth = () => {
  return <div className="twofact-container">
    {/* <TwoFactorSetup /> */}
    {/* <TwoFactorKey /> */}
    {/* <TwoFactorOtp /> */}
    <UserPermissions />
  </div>;
};

const TwoFactorSetup = () => {
  return (
    <div className="twofact-box-container">
      <img src={BackArrowLong} alt="back" className="twofact-back" />
      <div className="twofact-header">
        <div className="twofact-title"> Two step verification </div>
        <div className="twofact-text">
          Secure your account with two-step verification
        </div>
      </div>
      <img src={Lock} alt="lock" className="twofact-img" />
      <div className="twofact-text">
        Two step verification gives you additional security by requiring a
        verification code whenever you sign in on new device.
      </div>
      <img src={Mobile} alt="lock" className="twofact-img" />
      <div className="twofact-text">
        Your phone number or Authenticator App helps us keep your account secure
        by adding an additional layer of verification.
      </div>
      <div className="twofact-button"> Set up </div>
    </div>
  );
};

const TwoFactorKey = () => {
  return (
    <div className="twofact-box-container">
      <img src={BackArrowLong} alt="back" className="twofact-back" />
      <div className="twofact-header">
        <div className="twofact-title"> Two step verification </div>
        <div className="twofact-text">Set up an authenticator app</div>
      </div>
      <div className="twofact-text">
        1. Install Google Authenticator app or any other authenticator app of
        your choice on your mobile device.
      </div>
      <div className="twofact-text">
        2. Add your account to the authenticator app through the add new account
        flow.
      </div>
      <div className="twofact-text">
        3. Use "ERP" as the account name and enter this secret key.
      </div>

      <div className="twofact-key">YDGQ7JRVJCSDZV45454NDI5DWAD664WD
      <img src={Copy} alt="copy" className="twofact-copy" />
      </div>
      <div className="twofact-button"> Continue </div>
    </div>
  );
};

const TwoFactorOtp = () => {
    return (
      <div className="twofact-box-container">
        <img src={BackArrowLong} alt="back" className="twofact-back" />
        <div className="twofact-header">
          <div className="twofact-title"> Two step verification </div>
          <div className="twofact-text">Enter the 6-digit verification code generated by your Authenticator app</div>
        </div>
        <input type="text" className="twofact-otp" placeholder="Enter 6-digit code"/>
        <div className="twofact-button"> Continue </div>
      </div>
    );
  };

export default TwoFactorAuth;
